name: RestAPI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: REST Recorder
      uses: jirikuncar/recorder@v1
      with:
        # URL of an REST endpoint (application/json).
        endpoint: 'https://www.nlotto.co.kr/common.do?method=getLottoNumber&drwNo=898'
        jq : '.totSellamnt'
    - run: echo -e "${{ steps.stars.outputs.time }}\\t${{ steps.stars.outputs.response }}" | tee -a stars.tsv

