name: RestAPI

on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Get Lotto Result
      id: lotto
      uses: jirikuncar/recorder@v1
      with:
        endpoint: 'https://www.nlotto.co.kr/common.do?method=getLottoNumber&drwNo=898'
    - run: echo -e "${{ steps.lotto.outputs.response }}"

