name: RestAPI

on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
#     - name: Get Lotto Result
#       id: lotto
#       uses: jirikuncar/recorder@v1
#       with:
#         endpoint: 'https://www.nlotto.co.kr/common.do?method=getLottoNumber&drwNo=898'
#     - name: Show response
#       run: echo -e "${{ steps.lotto.outputs.response }}"
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run fetch
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

